
{% set name = "vcf2gwas" %}
{% set version = "0.5" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/frankvogt/vcf2gwas.git
  # url: https://github.com/frankvogt/vcf2gwas/releases/download/{{ version }}/vcf2gwas-{{ version }}.tar.gz

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  # "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or
  # "skip: True  # [not win]" to limit to Windows.
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  # script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .
  # noarch: python
  
  entry_points:
    #- vcf2gwas = vcf2gwas.__main__.main
    {% for entry in data['entry_points']['console_scripts'] %}
      - {{ entry.split('=')[0].strip() }} = {{ entry.split('=')[1].strip() }}
    {% endfor %}
  

requirements:
  # if you need compilers, uncomment these
  #    read more at https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html
  # build:
  #   - {{ compilers('c') }}
  host:
    - python==3.9
    - pip
    - numpy==1.20*
    - matplotlib==3.4*
    - scipy
    - scikit-learn
    - numba
    #- ipykernel
    #- jupyterlab
    - psutil==5.8*
    - pandas==1.2*
    - seaborn==0.11*
    - adjusttext==0.7*
    - bcftools==1.12*
    - plink==1.90*
    - gemma==0.98.3

  run:

    
    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
    {# raw is for ignoring templating with cookiecutter, leaving it for use with conda-build #}

test:
  #source_files:
    #- tests
  #requires:
    #- pytest
    #- pytest-cov
  #imports:
  #  - utils.py
  #  - parsing.py
  #commands:
  #  - test_vcf2gwas

about:
  home: https://github.com/frankvogt/vcf2gwas
  summary: Python API for comprehensive GWAS analysis using GEMMA
  license: {{ data.get('license') }}
  license_file: LICENSE
  dev_url: https://github.com/simplejson/simplejson
