{% set data = load_setup_py_data() %}

package:
  name: vcf2gwas
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/frankvogt/vcf2gwas.git

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python
  
  entry_points:
    {% for entry in data['entry_points']['console_scripts'] %}
      - {{ entry.split('=')[0].strip() }} = {{ entry.split('=')[1].strip() }}
    {% endfor %}
  

requirements:
  host:
    - python==3.9
    - pip3

  run:
    - python==3.9

    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:

about:
  home: https://github.com/frankvogt/vcf2gwas
  summary: Python API for comprehensive GWAS analysis using GEMMA
  license: {{ data.get('license') }}
  license_file: LICENSE
  dev_url: https://github.com/frankvogt/vcf2gwas
