{% set version = "0.8.9" %}

package:
  name: vcf2gwas
  version: {{ version }}

source:
  git_url: https://github.com/frankvogt/vcf2gwas.git

build:
  number: 0
  script: "python3.9 -m pip install . -vv"
  noarch: python
  
  entry_points:
    - vcf2gwas = vcf2gwas.__main__:run_main

requirements:
  host:
    - python==3.9
    - pip

  run:
    - python==3.9
    - numpy=1.23
    - pandas=1.5
    - matplotlib=3.7
    - seaborn=0.12
    - scikit-allel=1.3
    - scikit-learn=1.2
    - psutil=5.9
    - adjusttext=0.7
    - bcftools=1.17
    - plink=1.90
    - gemma==0.98.3

test:

about:
  home: https://github.com/frankvogt/vcf2gwas
  summary: Python API for comprehensive GWAS analysis using GEMMA
  license: GNUv3
  license_file: LICENSE
  dev_url: https://github.com/frankvogt/vcf2gwas
